version: '3.9'
networks:
  net:
    driver: bridge
services:
  server:
    image: ghcr.io/chroma-core/chroma:0.5.6.dev75
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - "8000:8000"
    networks:
      - net
    command: ["/bin/sh", "-c", "pip install numpy==1.26.3 && pip install chroma-hnswlib==0.7.3 && uvicorn chromadb.app:app --host 0.0.0.0 --port 8000 --workers 1"]
volumes:
  chroma-data:
    driver: local